#!/bin/sh
# Copyright (c) 2018 David Dahlberg <dyn+code@dahlberg.cologne>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

if [ $# -lt 2 ]; then
	echo "usage: $0 ACTION DAEMONS">&2
	exit 1
fi

action=$1
shift
daemons=$@

case "$action" in
	start|stop|restart|reload)
		for daemon in $daemons; do
			service $daemon $action
		done
		;;
	check)
		for daemon in $daemons; do
			service $daemon status
		done
		;;
	ls)
		lsarg=$daemons
		case "$lsarg" in
			all)	service --status-all;;
			off)	service --status-all| grep '^ \[ - \]';;
			on)	service --status-all| grep '^ \[ + \]';;
			*)
				echo "Unknown lsarg '$lsarg'">&2
				echo "Valid lsargs:">&2
				echo "  all">&2
				echo "  on">&2
				echo "  off">&2
				;;
		esac
		;;
	*)
		echo "Unknown action '$action'">&2
		echo "Valid actions:">&2
		echo "	start">&2
		echo "	stop">&2
		echo "	reload">&2
		echo "	restart">&2
		echo "	check">&2
		echo "	ls">&2
		exit 1
		;;
esac
