#!/bin/sh

unset force 

usage () {
	printf "usage:\n"
	printf " %s [-f] action daemon\n" "$(basename $0)"
	printf " %s enable|disable daemon\n" "$(basename $0)"
	printf " %s ls lsarg\n" "$(basename $0)"
}

while getopts 'f' opt; do
	case $opt in
	f|-f)	force=true;
		shift;;
	*)	printf "usage: %s [-nsr]\n" "$(basename $0)"
		exit 2;;
	esac
done

if [ $# -lt 2 ]; then
	echo "usage: $0 action daemons">&2
	exit 1
fi

action=$1
shift
daemons=$@

for daemon in $daemons; do
	case $daemon in
	ntpd)	 daemon=openntp;;
	smtpd)   daemon=opensmtpd;;
	sshd)	 daemon=ssh;;
	xntp)	 daemon=ntp;;
	*)	;;
	esac
	ndaemons="$ndaemons $daemon"
done
daemons=$(echo "$ndaemons" | sed 's/^ //')

case "$action" in
	check|disable|enable|stop|reload)
		for daemon in $daemons; do
			systemctl $action $daemon
		done
		;;
	start|restart)
		for daemon in $daemons; do
			if systemctl -q is-enabled $daemon || [ "$force" ]; then
				systemctl $action $daemon
			else
				printf "%s: need -f to force start since %s\n" \
				    "$daemon" \
				    "$(systemctl show $daemon --property UnitFileState)"
			fi
		done
		;;
	ls)
		lsarg=$daemons
		case "$lsarg" in
			all)	systemctl list-units --all;;
			failed)	systemctl list-units --state=failed;;
			off)	systemctl list-units --state=inactive;;
			on)	systemctl list-units --state=active;;
			started)	systemctl list-units;; 
			stopped)	systemctl list-units --state=exited;;
			*)
				echo "Unknown lsarg '$lsarg'">&2
				echo "Valid lsargs:">&2
				echo "  all">&2
				echo "  failed">&2
				echo "  off">&2
				echo "  on">&2
				echo "  started">&2
				echo "  stopped">&2
				;;
		esac
		;;
	*)
		echo "Unknown action '$action'">&2
		echo "Valid actions:">&2
		echo "	start">&2
		echo "	stop">&2
		echo "	reload">&2
		echo "	restart">&2
		echo "	check">&2
		echo "	ls">&2
		exit 1
		;;
esac
